# -*- coding: utf-8 -*-
"""22424363_Assignment1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CuFGNl8FBQPyKzkjzpknkOF93WydsiCE
"""

import networkx as nx

# Create a directed graph
G = nx.DiGraph()

# Add nodes
members = ["Harry", "Elton", "Asana", "Samuel", "Isaac"]
G.add_nodes_from(members)

# Define directed relationships (hypothetical)
relationships = [
    ("Harry", "Elton"),
    ("Harry", "Asana"),
    ("Asana", "Samuel"),
    ("Samuel", "Isaac"),
    ("Elton", "Isaac")
]
G.add_edges_from(relationships)

# --- Analysis ---
num_nodes = G.number_of_nodes()
num_edges = G.number_of_edges()
degrees = dict(G.degree())
in_degrees = dict(G.in_degree())
out_degrees = dict(G.out_degree())
isolated_nodes = list(nx.isolates(G))

# Print results
print("Number of nodes:", num_nodes)
print("Number of edges:", num_edges)
print("Degrees:", degrees)
print("In-degrees:", in_degrees)
print("Out-degrees:", out_degrees)
print("Isolated nodes:", isolated_nodes)

# --- Visualization ---
nx.draw(G,node_color="yellow",
        node_size=1300,
        with_labels=True,
        font_size=6,
        font_color="black"
       )